# Generated by Django 6.0.6 on 2026-07-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundFactSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True, verbose_name='Kode Produk')),
                ('ffs_date', models.DateField(verbose_name='Tanggal FFS')),
                ('data', models.JSONField(verbose_name='Data FFS Lengkap')),
                ('aum', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total AUM')),
                ('latest', models.BooleanField(default=True, verbose_name='Data Terbaru')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fund Fact Sheet',
                'verbose_name_plural': 'Fund Fact Sheets',
                'db_table': 'mutualfund_ffs',
            },
        ),
    ]
